name: MinecraftManhunt
version: '${project.version}'
main: me.matistan05.minecraftmanhunt.Main
api-version: 1.16
authors: [Matistan05]
description: Minecraft manhunt plugin made by Matistan
commands:
  manhunt:
    description: This command sets up the whole manhunt game
    usage: /<command>
permissions:
  manhunt.manhunt:
    description: Allows the player to use all /manhunt commands
    children:
      manhunt.add: true
      manhunt.remove: true
      manhunt.start: true
      manhunt.reset: true
      manhunt.list: true
      manhunt.help: true